name: Deploy PathExpression

on: [workflow_dispatch]

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deploy to Maven
    environment: Deploy
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy version
        uses: secure-software-engineering/actions/deployment/maven-deployment@maven-central-deploy
        with:
          java-distribution: adopt
          java-version: 11
          server-id: central
          server-username: ${{ secrets.SONATYPE_USER }}
          server-password: ${{ secrets.SONATYPE_PW }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          mvn-cli-args: '-DskipTests -Pdeployment'
          deploy-mode: release