name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: '8'
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
