name: Publish Release

on:
  pull_request:
    branches: [develop]
    types: [closed]
  push:
    branches: [develop]

jobs:
  publish:
    uses: secure-software-engineering/actions/release/maven-release-publish/action.yml@develop
    with:
      head_branch: develop
      java_version: '11'
      release_java_distribution: adopt
      deployment_environment: Deploy
      maven_deploy_args: '-DskipTests -Pdeployment'
    secrets:
      release_pat: ${{ secrets.AUTO_MERGE_PAT }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      maven_username: ${{ secrets.SONATYPE_USER }}
      maven_central_token: ${{ secrets.SONATYPE_PW }}
