name: Prepare Release
run-name: Release ${{ inputs.release_type }} triggered by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options: [major, minor, patch]

jobs:
  prepare-release:
    uses: secure-software-engineering/actions/release/maven-release-prepare/action.yml@develop
    with:
      release_type: ${{ inputs.release_type }}
      head_branch: develop
      java_version: '11'
    secrets:
      release_pat: ${{ secrets.AUTO_MERGE_PAT }}
