name: Release Process
on:
  push:
    branches: ['release/**', 'release-*']
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  handle-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: secure-software-engineering/actions/version@develop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          java_version: '11'
          java_distribution: 'temurin'
          target_branch: 'master'