name: Zombie Mode
on:
  schedule:
    - cron: '0 6 * * 1-5'

jobs:
  zombie-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: secure-software-engineering/actions/zombie-mode/prepare-pr@develop
        with:
          github-token: ${{secrets.AUTO_MERGE_PAT}}
          base-branch: develop
          merge-timeout-days: 3
          version-file: pom.xml


  auto-merge-aged:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: secure-software-engineering/actions/zombie-mode/merge-pr@develop
        with:
          github-token: ${{secrets.AUTO_MERGE_PAT}}
          merge-timeout-days: 3
          merge-method: squash
          delete-branch: true
          label: zombie-mode